-- =============================================================================
--  pg_explain_tool -- test fixtures for pg-explain-mcp PlanCheck adapters
-- =============================================================================
--
--  Creates empty tables + fill_* / clear_* procedures for each PlanCheck.
--  Data is loaded on demand:
--
--      CALL pg_explain_tool.fill_all(5000000);
--      CALL pg_explain_tool.fill_index_scan(5000000);
--
--  VACUUM is not run here (cannot run inside an extension transaction).
--  See fixtures/README.md for the manual VACUUM step.
-- =============================================================================

-- -----------------------------------------------------------------------------
--  IndexScanCheck
-- -----------------------------------------------------------------------------

create table data_index_scan_norm (
    id   bigserial primary key,
    val  text      not null,
    num  integer   not null,
    pad  text
);

create index idx_data_index_scan_norm_val on data_index_scan_norm (val);

create table data_index_scan_unclastered (
    id   bigserial primary key,
    val  text      not null,
    num  integer   not null,
    pad  text
);

alter table data_index_scan_unclastered set (autovacuum_enabled = false);

create index idx_data_index_scan_unclastered_val on data_index_scan_unclastered (val);

create procedure fill_index_scan(totalcount int)
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    insert into data_index_scan_norm (val, num, pad)
    select md5(j::text), (random() * 1_000_000)::int, repeat('x', 200)
    from generate_series(1, totalcount) as j;

    insert into data_index_scan_unclastered (val, num, pad)
    select md5(j::text), (random() * 1_000_000)::int, repeat('x', 200)
    from generate_series(1, totalcount) as j;

    for i in 1..20 loop
        update data_index_scan_unclastered
        set pad = repeat('y', 200)
        where id % 5 = 0;

        delete from data_index_scan_unclastered
        where id % 7 = 0 and id > totalcount / 10;

        insert into data_index_scan_unclastered (val, num, pad)
        select md5((totalcount * 2 + i * 100_000 + j)::text),
               (random() * 1_000_000)::int,
               repeat('z', 200)
        from generate_series(1, 50_000) as j;
    end loop;

    analyze data_index_scan_norm;
    analyze data_index_scan_unclastered;
end;
$$;

create procedure clear_index_scan()
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    truncate data_index_scan_norm, data_index_scan_unclastered restart identity;
end;
$$;


-- -----------------------------------------------------------------------------
--  SeqScanCheck
-- -----------------------------------------------------------------------------

create table data_seq_scan_norm (
    id   bigint generated by default as identity primary key,
    val  integer   not null,
    pad  text
);

create index idx_data_seq_scan_norm_val on data_seq_scan_norm (val);

create table data_seq_scan_nonindex (
    id   bigint generated by default as identity primary key,
    val  integer   not null,
    pad  text
);

-- no index on val — the planner is forced into a seq scan.

create procedure fill_seq_scan(totalcount int)
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    insert into data_seq_scan_norm (val, pad)
    select (random() * 1_000_000)::int, repeat('x', 200)
    from generate_series(1, totalcount) as i;

    insert into data_seq_scan_nonindex (val, pad)
    select (random() * 1_000_000)::int, repeat('x', 200)
    from generate_series(1, totalcount) as i;

    analyze data_seq_scan_norm;
    analyze data_seq_scan_nonindex;
end;
$$;

create procedure clear_seq_scan()
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    truncate data_seq_scan_norm, data_seq_scan_nonindex restart identity;
end;
$$;

-- -----------------------------------------------------------------------------
--  disk_spill_sort
-- -----------------------------------------------------------------------------

create table data_disk_spill_sort_norm (
    id   bigint generated by default as identity primary key,
    val  integer   not null,
    pad  text
);

create table data_disk_spill_sort_spill (
    id   bigint generated by default as identity primary key,
    val  integer   not null,
    pad  text
);

create procedure fill_disk_spill_sort(totalcount int)
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    -- norm: ~10k rows × 60 bytes ≈ 600 kB — fits in the default 4 MB work_mem
    insert into data_disk_spill_sort_norm (val, pad)
    select (random() * 1_000_000)::int, repeat('x', 50)
    from generate_series(1, 10000) as n;

    -- spill: 1M rows × 200 bytes ≈ 200 MB — spills to disk
    insert into data_disk_spill_sort_spill (val, pad)
    select (random() * 1_000_000)::int, repeat('x', 200)
    from generate_series(1, totalcount) as n;

    analyze data_disk_spill_sort_norm;
    analyze data_disk_spill_sort_spill;
end;
$$;

create procedure clear_disk_spill_sort()
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    truncate data_disk_spill_sort_norm, data_disk_spill_sort_spill restart identity;
end;
$$;

-- -----------------------------------------------------------------------------
--  disk_spill_hash
-- -----------------------------------------------------------------------------

create table data_disk_spill_hash_norm (
    id   bigint generated by default as identity primary key,
    val  text      not null,
    pad  text
);

create table data_disk_spill_hash_spill (
    id   bigint generated by default as identity primary key,
    val  text      not null,
    pad  text
);

create procedure fill_disk_spill_hash(totalcount int)
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    -- norm: 25k rows × ~96-byte key — hash table fits in work_mem
    insert into data_disk_spill_hash_norm (val, pad)
    select
        md5(n::text) || md5((n + 1)::text) || md5((n + 2)::text),
        repeat('x', 50)
    from generate_series(1, 25000) as n;

    -- spill: 1M rows × ~96-byte key — hash table exceeds work_mem
    insert into data_disk_spill_hash_spill (val, pad)
    select
        md5(n::text) || md5((n + 1)::text) || md5((n + 2)::text),
        repeat('x', 50)
    from generate_series(1, totalcount) as n;

    analyze data_disk_spill_hash_norm;
    analyze data_disk_spill_hash_spill;
end;
$$;

create procedure clear_disk_spill_hash()
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    truncate data_disk_spill_hash_norm, data_disk_spill_hash_spill restart identity;
end;
$$;

-- -----------------------------------------------------------------------------
--  nested_loop
-- -----------------------------------------------------------------------------

create table data_nested_loop_norm (
    id   bigserial primary key,
    val  integer   not null
);

create table data_nested_loop_many (
    id   bigserial primary key,
    val  integer   not null
);

create table data_nested_loop_inner (
    id   bigserial primary key,
    val  integer   not null,
    pad  text
);

create index idx_data_nested_loop_inner_val on data_nested_loop_inner (val);

create procedure fill_nested_loop(totalcount int)
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    -- outer, small: 100 rows → ~100 loop iterations
    insert into data_nested_loop_norm (val)
    select (random() * 1_000_000)::int
    from generate_series(1, 100) as n;

    -- outer, larger: 5000 rows → ~5000 loop iterations
    insert into data_nested_loop_many (val)
    select (random() * 1_000_000)::int
    from generate_series(1, 5000) as n;

    -- inner, indexed on val
    insert into data_nested_loop_inner (val, pad)
    select (random() * 1_000_000)::int, repeat('x', 200)
    from generate_series(1, totalcount) as n;

    analyze data_nested_loop_norm;
    analyze data_nested_loop_many;
    analyze data_nested_loop_inner;
end;
$$;

create procedure clear_nested_loop()
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    truncate data_nested_loop_norm, data_nested_loop_many, data_nested_loop_inner
        restart identity;
end;
$$;

-- -----------------------------------------------------------------------------
--  bitmap_heap_scan
-- -----------------------------------------------------------------------------

create table data_bitmap_heap_scan_norm (
    id   bigserial primary key,
    val  integer   not null,
    pad  text
);

create index idx_data_bitmap_heap_scan_norm_val
    on data_bitmap_heap_scan_norm (val);

create procedure fill_bitmap_heap_scan(totalcount int)
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    insert into data_bitmap_heap_scan_norm (val, pad)
    select (random() * 1_000_000)::int, repeat('x', 200)
    from generate_series(1, totalcount) as n;

    analyze data_bitmap_heap_scan_norm;
end;
$$;

create procedure clear_bitmap_heap_scan()
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    truncate data_bitmap_heap_scan_norm
        restart identity;
end;
$$;

-- -----------------------------------------------------------------------------
--  estimate_mismatch
-- -----------------------------------------------------------------------------

create table data_estimate_mismatch_norm (
    id   bigserial primary key,
    val  integer   not null,
    pad  text
);

create table data_estimate_mismatch_skewed (
    id   bigserial primary key,
    val  integer   not null,
    pad  text
);

create procedure fill_estimate_mismatch(totalcount int)
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
declare
    skew_freq real;
    skew_rows integer;
begin
    -- norm: uniform distribution, statistics match reality
    insert into data_estimate_mismatch_norm (val, pad)
    select (random() * 100)::int, repeat('x', 200)
    from generate_series(1, totalcount) as n;

    analyze data_estimate_mismatch_norm;

    -- skewed: uniform data, but we tell the planner it's heavily skewed
    insert into data_estimate_mismatch_skewed (val, pad)
    select (random() * 100)::int, repeat('x', 200)
    from generate_series(1, totalcount) as n;

    analyze data_estimate_mismatch_skewed;

    alter table data_estimate_mismatch_skewed set (autovacuum_enabled = false);


    -- now overwrite the statistics: pretend 95% of rows have val = 42
    skew_freq := 0.95;
    skew_rows := (totalcount * skew_freq)::int;

    perform pg_restore_attribute_stats(
        'schemaname', 'mcp_explain_tool',
        'relname',    'data_estimate_mismatch_skewed',
        'attname',    'val',
        'inherited',  false,
        'null_frac',  0.0::real,
        'avg_width',  4::integer,
        'n_distinct', 100::real,
        'most_common_vals',  '{42}'::text,
        'most_common_freqs', '{0.95}'::real[],
        'histogram_bounds',  '{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100}'::text
    );
end;
$$;

create procedure clear_estimate_mismatch()
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    truncate data_estimate_mismatch_norm, data_estimate_mismatch_skewed
        restart identity;
end;
$$;

-- -----------------------------------------------------------------------------
--  fixture parameters
-- -----------------------------------------------------------------------------
--
-- Constants used by multiple fixtures. In PostgreSQL there is no
-- "package variable", so a schema-level function serves the same
-- purpose: change the body, and every caller picks up the new value
-- on the next call (no restart, no recompile).

create or replace function partition_pruning_year() returns int
language sql immutable
as $$ select 2026 $$;

-- -----------------------------------------------------------------------------
--  partition_pruning
-- -----------------------------------------------------------------------------

create table data_partition_pruning (
    id   bigserial,
    ts   date    not null,
    val  integer not null,
    pad  text
) partition by range (ts);

create procedure create_monthly_partitions(
    parent_table text,
    year_start   int,
    year_end     int,
    schema_name  text default 'mcp_explain_tool'
)
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
declare
    y int;
    m int;
    part_name text;
    from_date date;
    to_date   date;
begin
    for y in year_start .. year_end loop
        for m in 1 .. 12 loop
            part_name := format(
                '%s_p%s%s',
                parent_table,
                to_char(y, 'FM0000'),
                to_char(m, 'FM00')
            );
            from_date := make_date(y, m, 1);
            to_date   := (from_date + interval '1 month')::date;

            execute format(
                'create table if not exists %I.%I partition of %I.%I '
                'for values from (%L) to (%L)',
                schema_name, part_name,
                schema_name, parent_table,
                from_date, to_date
            );
        end loop;
    end loop;
end;
$$;

create procedure fill_partition_pruning(totalcount int)
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
declare
    y int := partition_pruning_year();
begin
    call create_monthly_partitions('data_partition_pruning', y, y);

    insert into data_partition_pruning (ts, val, pad)
    select
        make_date(y, 1, 1) + (n % 365)::int,
        (random() * 1_000_000)::int,
        repeat('x', 200)
    from generate_series(1, totalcount) as n;

    analyze data_partition_pruning;
end;
$$;

create procedure clear_partition_pruning()
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    truncate data_partition_pruning restart identity;
end;
$$;

-- -----------------------------------------------------------------------------
--  non_sargable
-- -----------------------------------------------------------------------------

create table data_non_sargable (
    id     bigserial primary key,
    email  text      not null,
    pad    text
);

-- Plain index on email. Deliberately no functional index — the whole
-- point is that lower(email) = 'x' cannot use this index.
create index idx_data_non_sargable_email on data_non_sargable (email);

create procedure fill_non_sargable(totalcount int)
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    insert into data_non_sargable (email, pad)
    select
        'user' || lpad(n::text, 10, '0') || '@example.com',
        repeat('x', 200)
    from generate_series(1, totalcount) as n;

    analyze data_non_sargable;
end;
$$;

create procedure clear_non_sargable()
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    truncate data_non_sargable restart identity;
end;
$$;

-- -----------------------------------------------------------------------------
--  Aggregates (grow as adapters are added)
-- -----------------------------------------------------------------------------

-- -----------------------------------------------------------------------------
--  aggregates
-- -----------------------------------------------------------------------------

create procedure fill_all(totalcount int)
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    call fill_seq_scan(totalcount);
    call fill_index_scan(totalcount);
    call fill_disk_spill_sort(totalcount);
    call fill_disk_spill_hash(totalcount);
    call fill_nested_loop(totalcount);
    call fill_bitmap_heap_scan(totalcount);
    call fill_estimate_mismatch(totalcnt);
    call fill_partition_pruning(totalcnt);
    call fill_non_sargable(totalcnt);
end;
$$;

create procedure clear_all()
language plpgsql
set search_path = mcp_explain_tool, pg_catalog
as $$
begin
    call clear_seq_scan();
    call clear_index_scan();
    call clear_disk_spill_sort();
    call clear_disk_spill_hash();
    call clear_nested_loop();
    call clear_bitmap_heap_scan();
    call clear_estimate_mismatch();
    call clear_partition_pruning();
    call clear_non_sargable();
end;
$$;

